*** Settings ***
Library	Collections
Library	String
Library	RequestsLibrary

*** Variables ***
@{states}	Acknowledged	Closed
@{energyvalues}	0	1	2	5
${energyproduced}	0
${state}	Open

*** Test Cases ***
zero generation alerts
	${state}	Energy Loop Alerts

*** Keywords ***
Energy Loop Alerts
	FOR	${i}	IN RANGE	999999
		State Loop Alerts
		Exit For Loop if  '${energyproduced}' != '0'
	END
	Run Keyword if  '${energyproduced}' != '0'  Closed Email Alert

State Loop Alerts
	FOR	${j}	IN RANGE	999999
		Run Keyword If  '${state}' == 'Open'  Open Email Alert
		Sleep  1 sec
		#Sleep  1 day
		${tempenergyproduced}=  Evaluate  random.choice($energyvalues)  random
		set test variable  ${energyproduced}  ${tempenergyproduced}
		Log To Console  'State change for energy production energyproduced: ${energyproduced}'
		${tempstate}=  Evaluate  random.choice($states)  random
		set test variable  ${state}  ${tempstate}
		Log To Console  'User or System changed the Alert state to: ${state}'
		Exit For Loop If  '${state}' != 'Open'
	END

Open Email Alert
	Log  'New Alert: Zero Enegry Generated by the System, IMAP library can be used to send actual email'
	Log To Console  'New Alert: Zero Enegry Generated by the System'

Closed Email Alert
	Log  'Alert Cleared: Enegry is now Generated by the System, IMAP library can be used to send actual email'
	Log To Console  'Alert Cleared: Enegry is now Generated by the System'
